import type { AppAnalysis } from "@/types/app-analysis";

const TRACKER_HINTS = [
  { token: "firebase", name: "Firebase", purpose: "Analytics, crash reporting, messaging, or remote configuration." },
  { token: "facebook", name: "Meta SDK", purpose: "Ad attribution, login, sharing, and audience measurement." },
  { token: "google", name: "Google Services", purpose: "Ads, analytics, maps, sign-in, or platform services." },
  { token: "adjust", name: "Adjust", purpose: "Install attribution and campaign measurement." },
  { token: "appsflyer", name: "AppsFlyer", purpose: "Install attribution and marketing analytics." },
  { token: "branch", name: "Branch", purpose: "Deep links and attribution measurement." },
];

const CAPABILITY_MAP = [
  { token: "camera", capability: "Can request camera access.", flag: "Camera access deserves scrutiny if the core feature does not need photos or scanning." },
  { token: "microphone", capability: "Can request microphone access.", flag: "Microphone access is sensitive because it can capture audio from the device." },
  { token: "location", capability: "Can request location access.", flag: "Location access can reveal routines, places visited, and movement patterns." },
  { token: "contacts", capability: "Can request contact data.", flag: "Contact access can expose other people who never consented to the app." },
  { token: "bluetooth", capability: "Can interact with nearby Bluetooth devices.", flag: "Bluetooth access can be used for proximity signals and nearby device discovery." },
  { token: "sms", capability: "Can interact with SMS.", flag: "SMS access is unusually sensitive for most consumer apps." },
  { token: "storage", capability: "Can read or write local files.", flag: "File access can expose downloaded media, documents, or cached app data." },
];

export function buildLocalAnalysis(rawData: unknown): AppAnalysis {
  const text = JSON.stringify(rawData).toLowerCase();
  const permissions = extractPermissionText(rawData);
  const capabilities = new Set<string>();
  const redFlags = new Set<string>();

  for (const item of CAPABILITY_MAP) {
    if (text.includes(item.token) || permissions.some((permission) => permission.includes(item.token))) {
      capabilities.add(item.capability);
      redFlags.add(item.flag);
    }
  }

  const trackers = TRACKER_HINTS.filter((tracker) => text.includes(tracker.token)).map(({ name, purpose }) => ({
    name,
    purpose,
  }));

  const riskScore = Math.min(
    100,
    22 + redFlags.size * 12 + trackers.length * 7 + Math.min(permissions.length, 12) * 2,
  );

  return {
    riskScore,
    realityCheck:
      "This report is generated by AppXRay's local rules engine. It checks public metadata, permissions, scripts, and known tracker hints, so treat it as a transparent first-pass scan rather than a full reverse-engineering result.",
    physicalCapabilities:
      capabilities.size > 0
        ? Array.from(capabilities)
        : ["No high-signal physical device capabilities were visible in the scraped store metadata."],
    trackers:
      trackers.length > 0
        ? trackers
        : [{ name: "No obvious tracker named in metadata", purpose: "Store pages often omit bundled SDKs, so absence here is not proof of absence." }],
    redFlags:
      redFlags.size > 0
        ? Array.from(redFlags)
        : ["No obvious permission mismatch was visible from the scraped store metadata alone."],
    verdict: riskScore >= 70 ? "High Risk" : riskScore >= 42 ? "Use with Caution" : "Safe",
  };
}

function extractPermissionText(rawData: unknown): string[] {
  if (!rawData || typeof rawData !== "object") {
    return [];
  }

  const record = rawData as Record<string, unknown>;
  const permissions = record.permissions;

  if (!Array.isArray(permissions)) {
    return [];
  }

  return permissions.map((permission) => String(permission).toLowerCase());
}
